language: go
services:
- docker
go:
- 1.11.4
- tip
matrix:
  fast_finish: true
env:
  global:
  - PATH=$HOME/gopath/bin:$PATH
  - NOOP=true
  - EMAIL=test@echosoft.uk
  - secure: bn6PLat+cVx6mrwJJm/eWRhEI8tkaP2RRp7//x5yKMUeXy6LDhYK4vjyjVMJ44hyj+gjViF3yrtQlN0EXHk3h3Z8g1/9DHV95N2SXjU2Wx2N4lQ/arv71ntBHfzX5obL9t+pB5J+WhvXy4SXGgT8Oq/08wYtdqH2EpxCv2xEgMfBN6Nxt9l8dxzuu9buYDw1c0W805cIT4tm6KylqiIDDZmm+2S1OpdBKXBOFbi6O1RJppJ2GHI9irMHPvQTkCQKDp64R4y6/AAtuAuvHL7P1gYaEUbx1atCK+2kUWu6YftxE4MhkmZkNgggcrd0JkFhB8MuQr7q9emKYQIoZyWHXt32BoSXp7BTVkidejEq20pKiFiMfJxSmqu9FPCheG8x0Q8mB3ZfDvtctxh+NtOtx0MLwflR6+WcMllvvXpF9g8bvKEnyVq0rpUeMewc5Kwt0ConXr6Q1Lj0slMFq4lGidsuY5FzSZeH6Zev62SNeEDmwXxF3nF9RAClPrhOVJKcdh6qsG8tffR1FtbySKVn4eNut5FCLk50yaZNQMCOHXeazOqabMlnGN1NzWMGhJBwATJ3DNvErjwlLG7Q2FvHzwhdsBWds9nRTGl+uQJrFR5hqfdpeyvyhbTmV0dgw4JQKwo/2Wi+pVxv2py1Au/SP6uMaAm6zsy1VYpFxcZ+r1M=
  - secure: mSDGpszD4XNw3kPNJ4RsdoZ5ROm4an0iel6zQean9mAKQy+J9qMFtV+6CvoFRuvF77fdN43S5HMeI/gFtAOvM0twlVEHm3dkEVzjgc4DjB2Ey3SHdNu24Fu5C+CElyqz+Yim3YuegLy1jhcTruB2BvFyYwCs58Kplg5x8Vc/qikMffuqfTk9ISBW62r1wMhaq55IZ837asru5l2Ve+Jv9cFIUHj8rIuV6qbk73uH+sPjNL5uheV3GOLTd22MZJICZrlVkjZKouEuh9pM7iUWWnpscIGyEyqvcuNU3tGSWFFigC597TWD32WQJMFeyRc8MgBG6+z8k8DoZnlwcMEtnkhREolb1zyGcWvJFomAtNoGhA8VsPbJnUF2AmBic6RAj4bT8yTvCBqa8U7Uu9jzL+D/0S2MOOEHruK/exhUoVWXq81306V6eaOT+0Fw6aZ75Hta06buQg8Q6RgGXSbBtokLbpJOtcaEcFS13sCO7kq8pLRCLZaNiSk60jtjnlfSuuClk0jaCWEM3EHORF5/yNMLPXgH4ERWPTZtwpl2431TAUHuswutriX2EhXE3Ivb3x4sTAsparw+Q3YT+umgM1MN9lQhvCiGxJEr7Fuvx3Io+GCoPW7cm1Qi98OI24IHiAsjm3gn2sxhCyyNRk77cJzx4QtkHglN8VHIysgrWl4=
  - secure: LFShBYwIkeykrZUBYrASn/vX59WL2T8ddJgfPikZhkE6vli6a5yBsjYIRoxAsds+Ed9IMsMwMjVK4uW/YdGvvOxQJhlOCzH7O0y92apbHJdpNYWKK1Jx+L0+DHOf3z8COkoKFGZ5Z+P8tF6Sxz6X+Dx0AHOJ7KHyv6pRt+UsY8wL0ULhDG8k0tOCa1zjvGqfYdXfHdhknlURlkUOBZ/pRz44MQ5RkCjRcoIqrNambqFpmuHWdiVUxkJBp10Qpml9go4fA1CX9jdln80QjGfvvaNiaSGCH0RiNVIcTgAyg4hzG5pZAO9ab5Y6GK3O/x0Mr7GeFooHQ5nHGpUmox2n6WqFogKsErI6LspHhduTe7NQ4seyxGDtT1Ipdv5QtovliO57YDrOl3ZJikkF+G/iwDdJjMUabx69sdhHUdOeP+vPPDEoYMIcSAQKLxPZZ5APb7lwoavozUDSkEWOGDjvMDw5EEJQ0mrvdP5AI6Zo/e4ZXXIS2Kklc4pp0lOil0tpN5d81AZGSHi0NkkfAoRiHJXu9TKPuyDBzoUC/HiCbNfQQTrsKCpRJ4ayUqO2ReI0zg/MV93JTLPJ7UWIQ2uVdngrzK/4NevVepTUb1ZHKasoKNt4O3l8DpQM17Uyu8DPhunktLSWvKF2WmmY5W3LOK07G+8YLDaLOS+vR7O2NNg=
install:
- go get -t -v ./...
script:
- go build -o gogo-garage-opener.bin ./...
- go test -v ./...
