
language: go

go:
 - 1.11.4
 - tip

matrix:
  fast_finish: true

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

install:
 - cd gogo-garage-opener
 - go get -t -v ./...

script:
 - cd gogo-garage-opener
 - go build ./...
 - go test -v ./...
