language: go
services:
- docker
go:
- 1.12.9
- tip
matrix:
  fast_finish: true
env:
  global:
  - PATH=$HOME/gopath/bin:$PATH
  - NOOP=true
  - EMAIL=test@echosoft.uk
  - secure: eCy1GtotN6Of8HD/RX9hzXwS033/YPiveBvtpWdPXacCtxCmSCLBAEajEBolWZoMe2e+nuUqC8Q+vh+VdCxRaLkUQC+SjNudS6nyP9YjkJ35NmWrrIqoacRdDFbuR1HOV8qLfpLT4neoU5yN1illipF3PtQLHiWT/m30/sed1vvTSDShEd1wiA8s3gHniynMm4rX0cKHTaxvAOAvIPJmfarEY1rX7rprHrtbDw5crnuFtwB1P/VvrlKZhuGodTAH6QK4EATspNMKEWtvTfkhkGcuTRHKxTJ+FiEW7Jq3zNUGShnzYt3sB0bWmQktXtgKGzx2fRFnNdDO2rwx9lLQgVbiIQLREkM49Z/D+H2hjMnUxso5ZgSmHurTt2aykzlbHxx4j5F/waogOWku7/PB/QQt15rcoblvrOhQv4wy8xhyQzti1aNc7b/EqAcr5LwHjwWs3IVoMUBeVg4BK4PGZJUahzgIgR/dcRcWY7V3BonoO/KJLKflQp2vuxFiQpwyysJ23mpUhE9AX3OluDzXR5xJb2fOkHTsPNTt5ZAPlDp3+1JdEaOxsxZybaCLT1Q7gySb+BTKA8lxHxucjUPkmMeUjqyjcZLbrhbarjfIdi4VLfuTFg3KZ9MhdTXrOaMFlIZDbw+OzledvKQTquIreWOYqJnjUnMuT+g2Tr6cEB0=
  - secure: ISHPFmtml8r9/zUBJFVOotr+wYN2aJfSBz/SrQ8kd0gtWbQ/w76F1WMvY1XXobGSa1bh+wEPDvYVac5X6HvSPKC87YXlnZxHOuuGJs3DGVWrMQR7pmpgRmW5zwE3o9vIRpD+WvPfXPCROod0cbaY7oivq6JWjl+XU7UTHvttD1yY3BQDsNI21glJDduS2t8xSUIPasoKC+arBu8O+ptcHlBa16gVgLXzm9T7lqdK14AAbEfyQTva67XsPn0/3uUsv0sGxBKMsqha7N/DZwOHrdybzwJYcwAkwPNEfxUfj/suz9R88cNNRkrdMSX3Sx/HsSvU9SWMu+IgH+elohxK9mPrR9vKEjFFwe4o+0s8HnASpJiCr4xtD/E71vXi1WlA9DvGaHDUIHZ1Y1zC/Ui1KI1xQ3gWRdjNvBfLLKc4d4DwwtH3+jzNdunW6s71aeh2dOpkgpk1aLru12+EWYwjuc55aKLwgqrGD8qa5QhWBedQHsVotkOuJfkAiDLz6HKQ3HMyQoz4yFwKQ0H3od5QyPoLS9Bi3scsIZ7gQRhEuT+ToQcQnTrZFHrikrl5k1K5d+XbI5b7UdkGZnutBHyqYmttKQuT4acAs+iPQVvmB8ATnAiqPIRznzhrZbyP+GY/2GGuunDwKSx8h0Nu7nj8Cgc0xIc+iYILG/tY3UOx7pQ=
  - secure: s4jUK3Ou/AnFjBKNFm5PYSoX6znNRMuBLaK8cS7nUpSzcRAbiNhpAzeJmoWoa7+zWhseU613+rQBYy/4zMXhu73QvgTPwBgqAjHEHqCBIKQOnHB5OpF1YJr/D3EUZiXCeuELiTtyjj3Vu5D+LYWlpof9nu2E3pl0AOYSeZQI/9EaS3crjh2KXe1fE+duVvZz28JsKMHKT4xe8HLbFM9titzaX1UY+pwmQR1ijiRGRhCLhKzmICYRlQVwRPzuxh+tTyeDhRZFUzLhwgu3nmiqbnqP9xr3+IUEE93Y2I7B5aKY3H1TjXmM523JlN7PltHEcDbYpYrqM1vy/Uyb507Tmg6WkXkAxZ+pKCqxsN4oYYVkfOEfHXCJKwW5VX8EfeJ4b7mbRw8DO4qUkJxGKk4go7BrQK81a9Swzo5WJ/rKq8BtCPVDlQRyyDhvpv34YVqEyMB40MIYXuZCmDCcAMGEmU5vXm2T998RPF3oKZvB48uHHWqc1+HinBxGeypRNnMG36XOiofx69MmtXttjCSJgsDEin1setpHrvLX1NLKHwsMSXUJ9pCii56m8FHhFBME+OhbgJ0dV2uiBFdjPpQ126ovlGVKOqMAdZabhqrPZontCyn0s8Ynr6DK3T/A/Lg5TxFK1eSGf8SvCtfzMc8mv3paw56PTPxdEm/sriobMrE=
install:
- go get -t -v ./...
script:
- go build -o gogo-garage-opener.bin ./...
- go test -v ./...
