version: '3'
services:
  caddy:
    image: "elswork/arm-caddy"
    ports:
    - "443:443"
    - "80:80"
    volumes:
    - ./caddy:/etc/
    - $HOME/.caddy:/.caddy
    - /etc/ssl/certs/:/etc/ssl/certs/
    environment:
      - RS=${RS}
    restart: always
    logging:
        driver: json-file
        options:
            max-size: 50m
  gogo-garage-opener:
    privileged: true
    image: "benjjefferies/gogo-garage-opener"
    volumes:
      - $HOME/data:/var/gogo-garage-opener/data
      - /etc/ssl/certs:/etc/ssl/certs
    environment:
      - DB=/var/gogo-garage-opener/data/gogo-garage-opener.db
      - RELAY=${RELAY}
      - SWITCH=${SWITCH}
      - NOTIFICATION=5m
      - AUTOCLOSE=true
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - RS=${RS}
      - AS=${AS}
      - AWS_SES_ENDPOINT=${AWS_SES_ENDPOINT}
      - WEBHOOK_USERNAME=${WEBHOOK_USERNAME}
      - WEBHOOK_PASSWORD=${WEBHOOK_PASSWORD}
    restart: always
    logging:
        driver: json-file
        options:
            max-size: 50m