version: '3'
services:
  caddy:
    image: caddy:2.4.6-alpine
    ports:
    - "443:443"
    - "80:80"
    volumes:
    - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    - ./caddy:/data
    environment:
      - RS=${RS}
    restart: always
    logging:
        driver: json-file
        options:
            max-size: 50m
  gogo-garage-opener:
    privileged: true
    image: "benjjefferies/gogo-garage-opener:arm64v8"
    volumes:
      - $HOME/data:/var/gogo-garage-opener/data
      - /etc/ssl/certs:/etc/ssl/certs
    environment:
      - DB=/var/gogo-garage-opener/data/gogo-garage-opener.db
      - RELAY=${RELAY}
      - SWITCH=${SWITCH}
      - NOTIFICATION=5m
      - AUTOCLOSE=true
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - RS=${RS}
      - AS=${AS}
      - AWS_SES_ENDPOINT=${AWS_SES_ENDPOINT}
    restart: always
    logging:
        driver: json-file
        options:
            max-size: 50m
  service-discovery:
    privileged: true
    image: "benjjefferies/service-discovery:arm64v8"
    network_mode: host
    environment:
      - RS=${RS}
      - AS=${AS}
      - ZEROCONF_PORT=42424
    restart: always
    logging:
        driver: json-file
        options:
            max-size: 50m
